import { Component } from '@angular/core';

@Component({
  selector: 'app-work-gallery',
  templateUrl: './work-gallery.component.html',
  styleUrls: ['./work-gallery.component.scss']
})
export class WorkGalleryComponent {

  images: string[] = [
    '/assets/Gallery/hccb1.png',
    '/assets/Gallery/hccb2.png',
    '/assets/Gallery/hccb3.png',
    '/assets/Gallery/hccb4.png',
    '/assets/Gallery/hccb5.png',
    '/assets/Gallery/hccb6.png',
    '/assets/Gallery/hccb7.png',
    '/assets/Gallery/hccb8.png',
    '/assets/Gallery/hccb9.png',
    '/assets/Gallery/hccb10.png',
    '/assets/Gallery/hccb11.png',
    '/assets/Gallery/hccb12.png',
    '/assets/Gallery/hccb13.png',
    '/assets/Gallery/hccb14.png',
    '/assets/Gallery/hccb15.png',
    '/assets/Gallery/sms1.png',
    '/assets/Gallery/sms2.png',
    '/assets/Gallery/sms3.png',
    '/assets/Gallery/sms4.png',
    '/assets/Gallery/sms5.png',
    '/assets/Gallery/sms6.png',
    '/assets/Gallery/sms7.png',
    '/assets/Gallery/sms8.png',
    '/assets/Gallery/orifood1.png',
    '/assets/Gallery/orifood2.png',
    '/assets/Gallery/orifood3.png',
    '/assets/Gallery/oriclean1.png',
    '/assets/Gallery/oriclean2.png',
    '/assets/Gallery/oriclean3.png',
    '/assets/Gallery/pidilite1.png',
    '/assets/Gallery/pidilite2.png',
    '/assets/Gallery/pidilite3.png',
    '/assets/Gallery/pidilite4.png',
    '/assets/Gallery/unitedSpirites.png',
    '/assets/Gallery/unitedSpirites2.png',
    '/assets/Gallery/unitedSpirites3.png',
    '/assets/Gallery/unitedSpirites4.png',
    '/assets/Gallery/CPF1.png',
    '/assets/Gallery/CPF2.png',
    '/assets/Gallery/CPF3.png',
    '/assets/Gallery/CPF4.png',
    '/assets/Gallery/miller1.png',
    '/assets/Gallery/miller2.png',
    '/assets/Gallery/HFCL1.png',
    '/assets/Gallery/HFCL2.png',
    '/assets/Gallery/HFCL3.png',
    '/assets/Gallery/HFCL4.png',
    '/assets/Gallery/HFCL5.png',
    '/assets/Gallery/HFCL7.png',
    '/assets/Gallery/HFCL.png',
    '/assets/Gallery/HFCL9.png',
    '/assets/Gallery/HFCL10.png',
    '/assets/Gallery/HFCL12.png',
    '/assets/Gallery/ORIENT1.png',
    '/assets/Gallery/ORIENT2.png',
    '/assets/Gallery/ORIENT3.png',
    '/assets/Gallery/ORIENT4.png',
    '/assets/Gallery/ORIENT5.png',
    '/assets/Gallery/ORIENT6.png',
    '/assets/Gallery/orient10.png',
    '/assets/Gallery/orient11.png',
    '/assets/Gallery/orient12.png',
    '/assets/Gallery/orient13.png',
    '/assets/Gallery/orient14.png',
    // '/assets/Gallery/orient15.png',
    '/assets/Gallery/orient16.png',
    '/assets/Gallery/orient17.png',
    '/assets/Gallery/orient21.png',
    '/assets/Gallery/orient20.png',
    '/assets/Gallery/orient22.png',
    '/assets/Gallery/orient23.png',
    '/assets/Gallery/orient30.png',
    '/assets/Gallery/orient31.png',
    '/assets/Gallery/orient32.png',
    '/assets/Gallery/refra1.png',
    '/assets/Gallery/refra.png',
    '/assets/Gallery/refra3.png',
    '/assets/Gallery/refra4.png',
    '/assets/Gallery/refra5.png',
    '/assets/Gallery/ATC.png',
    '/assets/Gallery/ATC1.png',
    '/assets/Gallery/ATC3.png',
    '/assets/Gallery/ATC4.png',
    '/assets/Gallery/ATC10.png',
    '/assets/Gallery/ATC11.png',
    '/assets/Gallery/ATC12.png',
    '/assets/Gallery/ATC13.png',
    '/assets/Gallery/HFCL100.png',
    '/assets/Gallery/HFCL101.png',
    '/assets/Gallery/HFCL103.png',
    '/assets/Gallery/HFCL104.png',
    '/assets/Gallery/HFCL111.png',
    '/assets/Gallery/HFCL112.png',
    '/assets/Gallery/HFCL113.png',
    '/assets/Gallery/HFCL114.png',
    '/assets/Gallery/SARVARAYA1.png',
    '/assets/Gallery/SARVARAYA2.png',
    '/assets/Gallery/SARVARAYA3.png',
    '/assets/Gallery/SARVARAYA4.png',
    '/assets/Gallery/ASTRAL1.png',
    '/assets/Gallery/ASTRAL2.png',
    '/assets/Gallery/ASTRAL3.png',
    '/assets/Gallery/ASTRAL4.png',
    '/assets/Gallery/ASTRAL5.png',
    '/assets/Gallery/ASTRAL6.png',
    '/assets/Gallery/ASTRAL7.png',
    '/assets/Gallery/ASTRAL8.png',
    '/assets/Gallery/ASTRAL9.png',
    '/assets/Gallery/ASTRAL10.png',
    // '/assets/Gallery/ASTRAL11.png',
    '/assets/Gallery/ASTRAL12.png',
    '/assets/Gallery/ASTRAL13.png',
    '/assets/Gallery/ASTRAL14.png',
    // '/assets/Gallery/ASTRAL15.png',
    '/assets/Gallery/ASTRAL16.png',
    '/assets/Gallery/vermaFillingFood.jpg',
    '/assets/Gallery/vremaFilling.jpg',
  ];

  selectedImage: string | null = null;

  openImage(image: string) {
    this.selectedImage = image;
  }

  closeImage() {
    this.selectedImage = null;
  }
}
